#!/bin/bash  

filename:scp117
function:远程scp 文件 到117主机 （替换用户名，密码，IP）
usage:scp117 <filename>

expect -c "
        spawn scp -r $@ zhiyuan@192.168.7.117:~/test
  	expect {
    		\"*assword\" {set timeout 30; send \"123\r\";}
    		\"yes/no\" {send \"yes\r\"; exp_continue;}
  	}
        expect eof"
exit
