#!/usr/bin/expect
set timeout 20
set passwd 123
set passwderror 0

spawn scp ../cinnamon-settings-daemon_2.2.4+qiana-1cdos1.16nfs1_amd64.deb ../cinnamon-settings-daemon-dev_2.2.4+qiana-1cdos1.16nfs1_amd64.deb nfs@192.168.7.1:~

expect {
		"*assword:*" {
					if { $passwderror == 1 } { 
							puts "passwd is error"
							exit 2
					}
					set timeout 1000
					set passwderror 1
					send "$passwd\r"
					exp_continue
		}   
		"*es/no)?*" {
			send "yes\r"
			exp_continue
		}   
		timeout {
			puts "connect is timeout"
			exit 3
		}   
}

