Document: autowork
Title: Debian autowork Manual
Author: <insert document author here>
Abstract: This manual describes what autowork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/autowork/autowork.sgml.gz

Format: postscript
Files: /usr/share/doc/autowork/autowork.ps.gz

Format: text
Files: /usr/share/doc/autowork/autowork.text.gz

Format: HTML
Index: /usr/share/doc/autowork/html/index.html
Files: /usr/share/doc/autowork/html/*.html
